

server:
  port: 9002

spring:
  datasource:
    url: jdbc:postgresql://datachan.cvqh1dktya7v.us-east-1.rds.amazonaws.com:5432/project2DB
    username: datachan
    password: p4ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
      
      
      